### ISSUE TITLE
City search add type to search url

### ISSUE THREAD

**Issue by Bodo1981** [ricobeck/KFOpenWeatherMapAPI#2]
can you please add the type=like parameter to your search url or support an extra option for like searching.

e.g. /data/2.5/find?q="+param+ "&type=like&sort=population&cnt=30

with "type=like" cities are found when entering only a few characters of the city (-> "Lon" shows a list with all city containing "Lon")

**Comment by ricobeck** [comment]
good idea. i am going to add a param for this.

**Comment by ricobeck** [comment]
please check out develop branch and confirm.

**Comment by Bodo1981** [comment]
sorry, holidays :) i tested it and found two issues:

1) first the parameter is called "type" not "linke"
wrong: NSDictionary *params = [self parametersWithDictionary:@{@"q": phrase, @"cnt": @(results), @"linke": searchTypeValue}];
wright: NSDictionary *params = [self parametersWithDictionary:@{@"q": phrase, @"cnt": @(results), @"type": searchTypeValue}];

2) if you search for cities, there is not always a "rain":{"3h":0} in the received json file. because of that your search function results in nil with the following error: 
Incoming data was invalid [KFOWMRainModel initWithDictionary:]. Keys missing: {(
    next3h
)}

**Comment by ricobeck** [comment]
fixed in 0.2.4
