### ISSUE TITLE
temperatureType not read

### ISSUE THREAD

**Issue by Bodo1981** [ricobeck/KFOpenWeatherMapAPI#3]
i found another small issue. the temperatureType is not set when making requests, so you always receive the temperature in kelvin...

**Comment by ricobeck** [comment]
my intention was to calculate the values at display time to enable switching between types. in my application i am using it like this:

``` obj-c
- (NSNumber *)convertedValueForTemperatureValue:(NSNumber *)temperatureValue
{
    switch (self.openWeatherAPI.temperatureType)
    {
        case KFOWMTemperatureTypeCelcius:
            return [self kelvinToCelcius:temperatureValue];
            break;
        case KFOWMTemperatureTypeFahrenheit:
            return [self kelvinToFahrenheit:temperatureValue];
            break;
        default:
            break;
    }
    return @0;
}
```

the conversion methods are already in the controller but not made public. i am going to change that.

**Comment by Bodo1981** [comment]
good idea... thx for the quick answer
